{% set version = "1.4.4" %}

package:
  name: python-primesieve
  version: {{ version }}

source:
  fn: primesieve-{{ version }}.tar.gz
  url: https://pypi.python.org/packages/source/p/primesieve/primesieve-{{ version }}.tar.gz
  md5: 307c949fa34bc1d0725e04f972463a51

build:
  # Seem primesieve is encountering hangs on Windows with Python 2.7.
  # So, neither primesieve nor these Python bindings are built in that case.
  skip: true  # [win and py2k]
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  features:
    - vc10              # [win and py34]
    - vc14              # [win and py35]

requirements:
  build:
    - gcc               # [unix]
    - python
    - setuptools
    - cython
    - numpy x.x
    - primesieve

  run:
    - libgcc            # [unix]
    - python
    - numpy x.x
    - primesieve

test:
  imports:
    - primesieve

  commands:
    - python -c "import primesieve; assert primesieve.nth_prime(1) == 2"

about:
  home: https://github.com/hickford/primesieve-python
  license: MIT
  summary: Fast prime number generator. Python bindings for primesieve C/C++ library

extra:
  recipe-maintainers:
    - jakirkham
    - kimwalisch
