{% set name = "primesieve" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: da7d5f13e0c5949ef598642aa39fcd9aa84487b116d8ea7d5e3a47a6ed2936cb

build:
  skip: true  # [py<35]
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - primesieve
    - primesieve.numpy
  commands:
    - python -c "import primesieve; assert primesieve.nth_prime(1) == 2"
    - python -c "import primesieve.numpy; assert primesieve.numpy.n_primes(1)[0] == 2"

about:
  home: https://github.com/hickford/primesieve-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast prime number generator. Python bindings for primesieve C/C++ library.
  description: |
    Python bindings for the primesieve C++ library.  Generates primes orders of magnitude faster than any pure Python code!

extra:
  recipe-maintainers:
    - jakirkham
    - kimwalisch
    - brl0
