{% set name = "python-primesieve" %}
{% set pypiname = "primesieve" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypiname[0] }}/{{ pypiname }}/{{ pypiname }}-{{ version }}.tar.gz
  sha256: 948d9d9502cb45077834892c05d7ac2678834efeca0d39f328715591b27ab3d5

build:
  skip: true  # [py<35]
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - cython
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - primesieve
    - primesieve.numpy
  commands:
    - python -c "import primesieve; assert primesieve.nth_prime(1) == 2"
    - python -c "import primesieve.numpy; assert primesieve.numpy.n_primes(1)[0] == 2"

about:
  home: https://github.com/kimwalisch/primesieve-python
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast prime number generator. Python bindings for primesieve C/C++ library.
  description: |
    Python bindings for the primesieve C++ library.  Generates primes orders of magnitude faster than any pure Python code!
    Primesieve library license: BSD 2-Clause
    Primesieve library website: https://github.com/kimwalisch/primesieve

extra:
  recipe-maintainers:
    - jakirkham
    - kimwalisch
    - brl0
