{% set name = "primesieve" %}
{% set version = "1.4.4" %}

package:
  name: python-{{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 58bbff5c6928254e4fadd21ce324d8bae97aa706f72d69b1b0e1bf7ed6a1925c

build:
  # Seem primesieve is encountering hangs on Windows with Python 2.7.
  # So, neither primesieve nor these Python bindings are built in that case.
  skip: true  # [win and py2k]
  number: 1003
  script: python -m pip install --no-deps --ignore-installed . -vv
  features:
    - vc10              # [win and py34]
    - vc14              # [win and py35]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
    - numpy
    - primesieve
  run:
    - python
    - primesieve
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - primesieve

  commands:
    - python -c "import primesieve; assert primesieve.nth_prime(1) == 2"

about:
  home: https://github.com/hickford/primesieve-python
  license: MIT
  summary: Fast prime number generator. Python bindings for primesieve C/C++ library

extra:
  recipe-maintainers:
    - jakirkham
    - kimwalisch
