# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_c_compilerclangpython2.7
    - CONFIG=osx_c_compilerclangpython3.6
    - CONFIG=osx_c_compilerclangpython3.7
    - CONFIG=osx_c_compilertoolchain_cpython2.7
    - CONFIG=osx_c_compilertoolchain_cpython3.6
    - CONFIG=osx_c_compilertoolchain_cpython3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "qWDZ+Vcf+Nlka3NTlZACBIkohLAiSJ5f9un/QNSHwx3x8xVbacI+wnpSI8TYDOEGxzFk5cVozZxiFbfBk8+9v7rI2RTjtaNe45OH1Ze09KsUc3JMb3EaP+Yl9u/8cWErsBHTN6ljqftl2ac+E8rq0rgaH+k3Hn/3gWs/1yl/zFMQjyqPg/GuJez6Jrseg7yDlvjIigxfT3ifBZRhT8rmZHteQnHho5O+kh51TpArRmhMdpXCNRTDjkwe4ooe9Rx4PqJ1qv2da5q3EGYIN0dC2+w/7VrbZ3SPrWKK579JAYdIke1XYbng3z6gA4x79qH5Psu+lFyny6zk73u3xz/I7gvHl738WfKWspVIG4Vx0/xuwfLymE+dB5m82BSLMfcEQy7BlEVfdHN03WpFzO9RuEuZ3Vcg/zfqYUtEGo8VTx2+uL349uIIBF2ZsFve9IFwbRalep5Jzi6PEVG9uJG2PTm5wDhX0UQnGY3uuoppCa67zoux4AX151z6cufXNT7599cePRjmh3ni3LF+ACnK2yNHaFtyDOOau5W2m4Olo7Kv+4l5by7Jm6pUQZT+qllYtx/N5TATyFSX4YZgeCFALkDpmAy9qyXR/WSX/BvriN2WdjCez1W6vu1W5zPj1rimbwCRL6s7jitIES2l7mZ6dwzW9eAcRIPGtNcQZ0olMEI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml